name: deploy-development-wf
on: 
  push:
    branches:
      - develop
jobs:
  deploy-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Build Website
        run: npx parcel build "./src/home.html" --dist-dir "./dev" --public-url "./"
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dev"
          name: "develop-artifact"
  deploy-job:
    needs: deploy-build-job
    permissions:
      pages: write
      id-token: write
    environment: "development"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Build Artifacts on Github pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "develop-artifact"
          token: ${{github.token}}
