name: pr-validation-wf
on:
  pull_request:
    branches:
      - develop
jobs:
  Linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Install Html files
        run: npm install --save-dev htmlhint
      - name: Install Css files
        run: npm install --save-dev stylelint
      - name: Lint html files
        run: npx htmlhint "**/*.html"
      - name: Lint css files
        run: npx stylelint "**/*.css"
  Build-job:
    runs-on: ubuntu-latest
    steps:
     - name: Clone Repository
       uses: actions/checkout@v4
     - name: Build Website
       run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
